### ISSUE TITLE
Selection not working Perfectly

### ISSUE THREAD

**Issue by suriya104** [btate/BTAndroidWebViewSelection#2]
Hi,
this is an excellent work for selecting the text and highlighting the text in android webview
but
When i use these two below functions in the WebView

webView.getSettings().setLoadWithOverviewMode(true);
webView.getSettings().setUseWideViewPort(true);

webView selection not selecting the text in the correct position where we select?

**Comment by btate** [comment]
I see the issue you're talking about, but I'm not sure why that would be.  Definitely has something to do with the wide viewport.  There's an interface method window.TextSelection.jsError("error string"); that will let you send data to the app to print in log cat.  Might be worth dumping out the perceived selection in both the app and the javascript to see what kind of discrepancy there is when using that wide view port.

**Comment by suriya104** [comment]
Hi,
thank you! for your quick response, I found that when zooming the webPage also the selection not working perfectly. I am really confused of how to make it work.

**Comment by btate** [comment]
I got this fixed for the full zoom out.  Not working when you allow to user to zoom due to the fact that the zoom controls seem to interfere with my touch listeners.  In the mean time you can pull the new version or you can see what you need to change in your project [here](https://github.com/btate/BTAndroidWebViewSelection/commit/1a03612b6b9f03fea59ce4b51ef4a53f1368562b#src/com/brandontate/androidwebviewselection/BTWebView.java).

**Comment by suriya104** [comment]
Thanks btate its working fine now with all the devices and also for zoom in and zoom out, but if the text gets selected simultaneously when we move the handle then it will be so good.
